# Conclusion

Cette période de ce stage un peu particulier s'achève et ce rapport essaie de rendre compte au plus juste possible du travail effectué durant ces mois de printemps et d'été. Nous avons pu voir qu'en amont du traitement de la data, il y a l'acquisition de celle-ci et que cette tâche était au moins aussi importante. J'ai passé sous silence une grosses partie des problèmes techniques rencontrés et autres pannes^[mention spéciale à la climatisation des serres, H-S plusieurs semaines à partir de mi-juillet.]. Pour autant, ces contraintes font parties du métier et l'analyste doit savoir s'y plier en ne maudissant que modérément l'expérimentateur, lorsque ce n'est pas lui-même. Il doit être présent dans le projet dés le début et participer à l'élaboration théorique de l'expérience.  

Il est aussi crucial de maîtriser la technique de l'instrument de mesure. Par exemple, en spectroscopie optique les pics peuvent avoir un décalage en longueur d'ondes qui traduit un effet de contrainte sur l'échantillon. Ce décalage ne peut pas exister en spectrométrie de masse, ou alors de façon discrète modulo 1,007 Da qui correspond à la masse d'un proton.  

Une fois cela acquis et mis en œuvre, les outils numériques ne manquent pas pour décortiquer les données. Je pourrais en ajouter à l'arsenal de proVOC, comme par exemple la PLS (et ses variantes) pour effectuer des régressions. Je me suis attardé pour l'instant à la découverte de la MCR et de l'ICA qui sont moins connues des utilisateurs et qui, de fait, demandent un plus grand travail d'accompagnement pour leur utilisation. Nous avons pu voir les avantages de telles méthodes.  

Avant cette année de master, je connaissais très peu de choses sur "les modèles linéaires généralisés", les "séries temporelles et spatiales", les "plans d'expériences". Bien qu'il me faudra quelques contorsions du cortex pour intégrer ces connaissances théoriques obtenues à ma pratique quotidienne, je ne doute pas qu'elles me seront utiles dans un futur proche.  

À travers ce rapport, j'espère avoir synthétisé correctement six mois de travaux effectués par un physicien dans un contexte à la frontière entre les mathématiques, l'environnement et la chimie. Cette interdisciplinarité, que je recherche depuis la fin de mon master 2 de photonicien, demande un apprentissage lent mais constant et une volonté permanente de vouloir sortir de sa zone de confort. C'est avant tout un goût pour la découverte et des aventures scientifiques que je recommande à chacun. 


# Remerciements {-}

Je tenais à remercier Jean-Michel Roger et Nicolas Barthes qui ont bien voulu accepter d'encadrer ce stage. Une chose me dit qu'on a pas fini de faire de la chimiométrie avec tous nos machin-MS. 

Pour continuer sur la chimiométrie, je remercie la team de Chemhouse et en particulier Silvia Mas-Garcia et Douglas Rutledge (et leur très léger accent respectif) pour leurs aides et conseils.  

Je salue également les autres membres de la PACE : Anne-Genevieve, Raphaelle, Bruno, Patrick et Benoit ; pour la sympathie au quotidien. Il en va de même pour tous les membres du CEFE^[et de Boris qui doit se contenter d'une note de bas de page.] avec qui je travaille régulièrement ou avec qui je partage des moments chaleureux. Mes pensées vont plus précisément vers Magali, Candice, Cao Li et Anjélica. Et merci aux relecteurs de ce rapport.  

Ce rapport conclu un semestre de stage mais également une année de formation continue. Avant septembre 2020, mes dernières heures de cours en tant qu'étudiant dataient de décembre 2011. Depuis cette date, j'ai moi-même enseigné en tant que vacataire à l'IUT durant mes années de thèses. Puis après d'autres contrats, j'ai été embauché à l'Université de Montpellier comme ingénieur. Ainsi en septembre 2020, j'étais tout à la fois néo et ancien étudiant, camarade et collègue. Pour moi qui n'était que de passage, la difficulté des cours à distance m'a affecté mais ne remettait pas en cause ni mon métier principal ni mon cursus universitaire. Pour autant je félicite l'effort des professeurs qui ont su s'adapter avec le peu de moyens mis à leur disposition. Je salue tout autant les étudiants en formation initiale qui jouent leur avenir professionnel.   

Enfin, je remercie les copains qui m'ont soutenu pendant l'année. Je déconseille vivement d'accumuler reprise d'étude + travail + confinement/couvre feu + concours de la fonction publique + travaux de rénovation. C'est trop. En particuliers, merci à Ryad, Jean-Michel et Nicolas (encore eux) pour leur aide lors des concours et à Bruce Dickinson, Steve Harris et les autres pour m'avoir accompagné durant l'écriture des multiples rapports.   

Merci aussi à ceux qui m'ont ajouté du travail durant cette année : Ngoc qui fut une brillante élève de conduite supervisée et qui n'a failli nous tuer que deux fois, à Batro pour avoir eu la brillante idée de synchroniser la date de sortie de notre jeu[@artho_2020] avec la date du deuxième confinement, et aux créatures de la nuit qu'il faut nourrir d'idées nouvelles chaque semaine.   

Enfin merci à Hélène pour me supporter depuis tout ce temps, pour son soutien et pour son aide.

`r if (knitr:::is_html_output()) '# References {-}'`